---
- name: Update packages cache
  apt:
    update_cache: yes

- name: Upgrade APT to the latest packages
  apt: 
    upgrade: safe

- name: Install required packages
  apt: state=present pkg={{ ubuntu_common_required_packages }}

- name: Install optional packages
  apt: state=present pkg={{ ubuntu_common_optional_packages }}

- name: Adjust APT update intervals
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic