---
- name: Check if we're using the default SSH port
  wait_for:
    port: 22
    state: started
    host: "{{ inventory_hostname }}"
    connect_timeout: 5
    timeout: 10
  delegate_to: localhost
  ignore_errors: yes
  register: default_ssh_port
  become: false

- name: Set inventory ansible_port to default (if previous task was completed successfully - port 22 reachable)
  set_fact:
    ansible_port: 22
  when: default_ssh_port is defined
  register: ssh_port_set

- name: Check if we're using custom provided SSH port (default hiveos role vars)
  wait_for:
    port: "{{ custom_ssh_port }}"
    state: started
    host: "{{ inventory_hostname }}"
    connect_timeout: 5
    timeout: 10
  delegate_to: "localhost"
  register: custom_ssh_port_check
  ignore_errors: yes
  become: false
  when: custom_ssh_port is defined and (default_ssh_port is undefined or default_ssh_port.state is undefined)

- name: Custom SSH port is found and configured properly (reachable)
  debug:
    msg: "Custom SSH port is already set to {{ custom_ssh_port }}"
  when: custom_ssh_port_check is defined and
        custom_ssh_port_check.state is defined and
        custom_ssh_port_check.state == "started"
  register: ssh_port_set

- name: Check if we're using the inventory-provided SSH port (in hosts file)
  wait_for:
    port: "{{ ansible_port }}"
    state: started
    host: "{{ inventory_hostname }}"
    connect_timeout: 5
    timeout: 10
  delegate_to: "localhost"
  ignore_errors: yes
  register: configured_ssh_port
  become: false
  when: ansible_port is defined and (( default_ssh_port is defined and default_ssh_port.state is undefined) or
        ( custom_ssh_port_check is undefined or custom_ssh_port_check.state is undefined))

- name: Ansible inventory SSH port is configured properly (reachable)
  debug:
    msg: "SSH port is configured properly"
  when: configured_ssh_port is defined and
        configured_ssh_port.state is defined and
        configured_ssh_port.state == "started"
  register: ssh_port_set

- name: Fail if SSH port was not auto-detected (unknown)
  fail:
    msg: "The SSH port is neither 22 or the one you provided in hosts file."
  when: ssh_port_set is undefined

- name: Ensure we use the configured SSH port for the remainder of the role (if it is already changed)
  set_fact:
    ansible_port: "{{ custom_ssh_port }}"
  when: custom_ssh_port_check is defined and
        custom_ssh_port_check.state is defined and
        custom_ssh_port_check.state == "started"

- name: Confirm host connection works (sanity check)
  ping:

- name: Setup alternate SSH port
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port "
    line: "Port {{ custom_ssh_port }}"
    state: present
  notify: "Restart ssh"

- name: Ensure SSH is reloaded if need be
  meta: flush_handlers

- name: Ensure we use the configured SSH port for the remainder of the role (if it was default 22)
  set_fact:
    ansible_port: "{{ custom_ssh_port }}"
  when: custom_ssh_port_check is undefined

- name: Run deferred setup to gather facts
  setup: